### PR TITLE
I pimped out your Searchable plugin

### PR DESCRIPTION
**Pull request by josegonzalez**
Feel free to peruse the commits. You'll also want to update the links in the readme. Note that I still have a few documentation additions and docblocking to do.

The Sanitization of the search term may also break your existing searches, so be warned.

### CODE REVIEW

**Comment by josegonzalez** [comment]
I've added some unit tests to the Helper (100%) and the Behavior (94.48%). Will add tests for the component, included model, and included controller as well, but for now it's pretty complete and usable.

**Comment by josegonzalez** [comment]
Closing. Sad panda bear.

**Comment by neilcrookespm** [comment]
Crap, sorry mate. I wasn't aware it was open. I never had time to peruse your plethora commits. If people are still using this plugin, and want the pull request merged, I will happily do so. Else, can they just use your fork?

**Comment by neilcrookes** [comment]
Crap, sorry mate. I wasn't aware it was open. I never had time to peruse your plethora commits. If people are still using this plugin, and want the pull request merged, I will happily do so. Else, can they just use your fork?

**Comment by josegonzalez** [comment]
Probs not worth it at this point, 2.x isn't even the stable release anymore :)

**Pull request closed without merging**
